#!/usr/bin/env python3
"""Deterministically generates db/seeds/0003_events_synthetic.sql.

Two fictional dev events with a 4-team double-elimination bracket each,
CDL map/mode rotation (HP, SnD, CTL, HP, SnD), consistent scores, and
pseudo-random-but-plausible per-map stat lines. All stats are SYNTHETIC.

Re-run after editing:  python3 db/seeds/generate_fixtures.py
"""
from __future__ import annotations

import random
from pathlib import Path

random.seed(20260718)

TEAMS = ["OpTic Texas", "Atlanta FaZe", "Toronto Ultra", "LA Thieves"]
ROSTERS = {
    "OpTic Texas": ["Shotzzy", "Dashy", "Pred", "Kenny"],
    "Atlanta FaZe": ["Simp", "aBeZy", "Cellium", "Drazah"],
    "Toronto Ultra": ["CleanX", "Insight", "Scrap", "Envoy"],
    "LA Thieves": ["Ghosty", "Kremp", "Gwinn", "JoeDeceives"],
}
MODE_ROTATION = ["hardpoint", "search-and-destroy", "control", "hardpoint", "search-and-destroy"]
MAP_POOLS = {
    "hardpoint": ["Hacienda", "Protocol", "Red Card", "Rewind", "Skyline", "Vault"],
    "search-and-destroy": ["Dealership", "Hacienda", "Protocol", "Red Card", "Rewind"],
    "control": ["Hacienda", "Protocol", "Vault"],
}

EVENTS = [
    # (name, start_date, is_lan, location) — fictional dev events
    ("Dev Fixture Major A 2025", "2025-02-01", True, "Arlington, TX"),
    ("Dev Fixture Major B 2025", "2025-03-15", True, "Boston, MA"),
]

# 4-team double elim: (round_label, stage, hi_seed_idx, lo_seed_idx) — winners
# resolved as we go; simple fixed outcomes per event via rng.
BRACKET = [
    ("WB R1", "Winners Bracket"),
    ("WB R1", "Winners Bracket"),
    ("WB Final", "Winners Bracket"),
    ("LB R1", "Losers Bracket"),
    ("LB Final", "Losers Bracket"),
    ("Grand Final", "Grand Final"),
]


def sql_str(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def game_score(mode: str, winner_is_t1: bool) -> tuple[int, int]:
    if mode == "hardpoint":
        w, l = 250, random.randint(120, 240)
    elif mode == "search-and-destroy":
        w, l = 6, random.randint(0, 4)
    else:
        w, l = 3, random.randint(0, 2)
    return (w, l) if winner_is_t1 else (l, w)


def stat_line(mode: str, won: bool) -> dict[str, int | None]:
    bump = 2 if won else 0
    if mode == "hardpoint":
        return dict(
            kills=random.randint(18, 30) + bump, deaths=random.randint(18, 28),
            assists=random.randint(2, 9), damage=random.randint(3200, 5200),
            hill_time=random.randint(25, 115), first_bloods=None,
            plants=None, defuses=None, ticks=None,
        )
    if mode == "search-and-destroy":
        return dict(
            kills=random.randint(3, 10) + (1 if won else 0), deaths=random.randint(3, 8),
            assists=random.randint(0, 3), damage=random.randint(600, 1500),
            hill_time=None, first_bloods=random.randint(0, 3),
            plants=random.randint(0, 2), defuses=random.randint(0, 1), ticks=None,
        )
    return dict(
        kills=random.randint(14, 26) + bump, deaths=random.randint(14, 24),
        assists=random.randint(2, 8), damage=random.randint(2500, 4200),
        hill_time=None, first_bloods=None, plants=None, defuses=None,
        ticks=random.randint(0, 8),
    )


def main() -> None:
    out: list[str] = [
        "-- GENERATED by generate_fixtures.py — do not edit by hand.",
        "-- SYNTHETIC dev fixtures: fictional events, fabricated stat lines.",
        "BEGIN;",
        "",
        "INSERT INTO seasons (year, title_id, league)",
        "SELECT 2025, id, 'CDL' FROM titles WHERE short_name = 'BO6'",
        "ON CONFLICT DO NOTHING;",
        "",
    ]

    for ev_i, (ev_name, start, is_lan, loc) in enumerate(EVENTS):
        ev = f"ev{ev_i}"
        out += [
            f"-- ===== {ev_name} =====",
            "WITH season AS (SELECT s.id FROM seasons s JOIN titles t ON t.id = s.title_id"
            " WHERE s.year = 2025 AND t.short_name = 'BO6' AND s.league = 'CDL')",
            f"INSERT INTO events (season_id, name, tier, start_date, end_date, location, is_lan, prize_pool)",
            f"SELECT id, {sql_str(ev_name)}, 'S', {sql_str(start)}, {sql_str(start)}::date + 2, "
            f"{sql_str(loc)}, {str(is_lan).lower()}, 500000 FROM season;",
            "",
        ]

        # resolve a plausible double-elim flow
        seeds = TEAMS[:]
        random.shuffle(seeds)
        wb1 = (seeds[0], seeds[3])
        wb2 = (seeds[1], seeds[2])
        w1, l1 = (wb1[0], wb1[1]) if random.random() < 0.6 else (wb1[1], wb1[0])
        w2, l2 = (wb2[0], wb2[1]) if random.random() < 0.6 else (wb2[1], wb2[0])
        wbf_w, wbf_l = (w1, w2) if random.random() < 0.5 else (w2, w1)
        lb1_w = l1 if random.random() < 0.5 else l2
        lb1_l = l2 if lb1_w == l1 else l1
        lbf_w, lbf_l = (wbf_l, lb1_w) if random.random() < 0.6 else (lb1_w, wbf_l)
        gf_w, gf_l = (wbf_w, lbf_w) if random.random() < 0.65 else (lbf_w, wbf_w)

        matchups = [wb1, wb2, (w1, w2), (l1, l2), (wbf_l, lb1_w), (wbf_w, lbf_w)]
        winners = [w1, w2, wbf_w, lb1_w, lbf_w, gf_w]
        placements = {gf_w: (1, 1), gf_l: (2, 2), lbf_l: (3, 3), lb1_l: (4, 4)}

        # create the three stages once per event
        for st_i, st_name in enumerate(["Winners Bracket", "Losers Bracket", "Grand Final"]):
            out += [
                f"INSERT INTO stages (event_id, name, ordinal)",
                f"SELECT id, {sql_str(st_name)}, {st_i} FROM events WHERE name = {sql_str(ev_name)};",
            ]
        out.append("")

        for s_i, ((round_label, stage), winner) in enumerate(zip(BRACKET, winners)):
            t1, t2 = matchups[s_i]
            t1_wins_series = winner == t1
            loser_maps = random.randint(0, 2)
            n_games = 3 + loser_maps
            # loser takes maps at random positions (never the last map)
            loser_positions = set(random.sample(range(n_games - 1), loser_maps))
            s1, s2 = (3, loser_maps) if t1_wins_series else (loser_maps, 3)
            sid = f"{ev}s{s_i}"

            out += [
                f"WITH stg AS (SELECT s.id, s.event_id FROM stages s"
                f" JOIN events e ON e.id = s.event_id"
                f" WHERE e.name = {sql_str(ev_name)} AND s.name = {sql_str(stage)})",
                f"INSERT INTO series (stage_id, event_id, team1_id, team2_id, team1_score, team2_score, best_of, played_at, round_label, liquipedia_match_id)",
                f"SELECT stg.id, stg.event_id, t1.id, t2.id, {s1}, {s2}, 5, "
                f"{sql_str(start)}::date + {s_i // 3} + time '12:00' + interval '{(s_i % 3) * 2} hours', "
                f"{sql_str(round_label)}, {sql_str('dev-' + sid)}",
                f"FROM stg, teams t1, teams t2 WHERE t1.name = {sql_str(t1)} AND t2.name = {sql_str(t2)};",
                "",
            ]

            for g_i in range(n_games):
                mode = MODE_ROTATION[g_i]
                map_name = random.choice(MAP_POOLS[mode])
                t1_wins_game = (g_i in loser_positions) != t1_wins_series  # XOR
                g1, g2 = game_score(mode, t1_wins_game)
                game_winner = t1 if t1_wins_game else t2
                out += [
                    f"INSERT INTO games (series_id, ordinal, map_id, mode_id, team1_score, team2_score, winner_team_id)",
                    f"SELECT s.id, {g_i + 1}, m.id, gm.id, {g1}, {g2}, w.id",
                    f"FROM series s, maps m JOIN titles ti ON ti.id = m.title_id, game_modes gm, teams w",
                    f"WHERE s.liquipedia_match_id = {sql_str('dev-' + sid)}",
                    f"  AND m.name = {sql_str(map_name)} AND ti.short_name = 'BO6'",
                    f"  AND gm.slug = {sql_str(mode)} AND w.name = {sql_str(game_winner)};",
                ]
                for team in (t1, t2):
                    won = team == game_winner
                    for handle in ROSTERS[team]:
                        st = stat_line(mode, won)
                        cols = ", ".join(k for k in st)
                        vals = ", ".join("NULL" if v is None else str(v) for v in st.values())
                        out += [
                            f"INSERT INTO game_player_stats (game_id, player_id, team_id, {cols})",
                            f"SELECT g.id, p.id, t.id, {vals}",
                            f"FROM games g JOIN series s ON s.id = g.series_id, players p, teams t",
                            f"WHERE s.liquipedia_match_id = {sql_str('dev-' + sid)} AND g.ordinal = {g_i + 1}",
                            f"  AND p.handle = {sql_str(handle)} AND t.name = {sql_str(team)};",
                        ]
                out.append("")

        for team, (pmin, pmax) in placements.items():
            prize = {1: 200000, 2: 120000, 3: 100000, 4: 80000}[pmin]
            out += [
                f"INSERT INTO event_placements (event_id, team_id, placement_min, placement_max, prize)",
                f"SELECT e.id, t.id, {pmin}, {pmax}, {prize} FROM events e, teams t",
                f"WHERE e.name = {sql_str(ev_name)} AND t.name = {sql_str(team)};",
            ]
        out.append("")

    out.append("COMMIT;")
    dest = Path(__file__).parent / "0003_events_synthetic.sql"
    dest.write_text("\n".join(out) + "\n")
    print(f"wrote {dest} ({len(out)} lines)")


if __name__ == "__main__":
    main()
